name: Build and Release GoPro Graber

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bleak httpx tqdm pyinstaller

    - name: Build the executable
      run: pyinstaller --onefile --name GoProGraber --icon=icon.ico GP_graber.py

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/GoProGraber.exe